const CompanysList = [
    {
        nombre: 'UNIVERSIDAD POLITECNICA DE TAPACHULA',
        rfc: 'UPT101105P97',
        tel_c: '962 689 0090',
        titular: 'JHONNY ROBERT MIS MAY',
        cargo: 'RECTOR',
        nombre_e: 'MARÍA CRISTINA RODRIGO RAMOS',
        tel_e: 'EXT. 4',
        correo_e: 'VINCULACION@UPTAPACHULA.EDU.MX',
        entidad: 'CHIAPAS',
        ciudad: 'TAPACHULA',
        cp: '30830',
        colonia: 'SC',
        calle: 'CARRETERA TAPACHULA - PUERTO MADERO KM. 24 + 300',
        numero: 'SN',
        estado: true
    },
    {
        nombre: 'UNIVERSIDAD POLITECNICA DE TAPACHULA2',
        rfc: 'UPT101105P98',
        tel_c: '962 689 0090',
        titular: 'JHONNY ROBERT MIS MAY',
        cargo: 'RECTOR',
        nombre_e: 'MARÍA CRISTINA RODRIGO RAMOS',
        tel_e: 'EXT. 4',
        correo_e: 'VINCULACION@UPTAPACHULA.EDU.MX',
        entidad: 'CHIAPAS',
        ciudad: 'TAPACHULA',
        cp: '30830',
        colonia: 'SC',
        calle: 'CARRETERA TAPACHULA - PUERTO MADERO KM. 24 + 300',
        numero: 'SN',
        estado: true
    },
    {
        nombre: 'UNIVERSIDAD POLITECNICA DE TAPACHULA3',
        rfc: 'UPT101105P99',
        tel_c: '962 689 0090',
        titular: 'JHONNY ROBERT MIS MAY',
        cargo: 'RECTOR',
        nombre_e: 'MARÍA CRISTINA RODRIGO RAMOS',
        tel_e: 'EXT. 4',
        correo_e: 'VINCULACION@UPTAPACHULA.EDU.MX',
        entidad: 'CHIAPAS',
        ciudad: 'TAPACHULA',
        cp: '30830',
        colonia: 'SC',
        calle: 'CARRETERA TAPACHULA - PUERTO MADERO KM. 24 + 300',
        numero: 'SN',
        estado: true
    },
    {
        nombre: 'UNIVERSIDAD POLITECNICA DE TAPACHULA4',
        rfc: 'UPT101105P90',
        tel_c: '962 689 0090',
        titular: 'JHONNY ROBERT MIS MAY',
        cargo: 'RECTOR',
        nombre_e: 'MARÍA CRISTINA RODRIGO RAMOS',
        tel_e: 'EXT. 4',
        correo_e: 'VINCULACION@UPTAPACHULA.EDU.MX',
        entidad: 'CHIAPAS',
        ciudad: 'TAPACHULA',
        cp: '30830',
        colonia: 'SC',
        calle: 'CARRETERA TAPACHULA - PUERTO MADERO KM. 24 + 300',
        numero: 'SN',
        estado: false
    }
]

export default CompanysList