
const  Projects = [
    {
        nombre: "Desarrollo de Sistema de Administración de Ventas",
        objetivo: "Desarrollar e implentar un sistema de administración de ventas para optimizar los procesos de gestión de ventas de servicios académicos",
        justificacion: "Garantizar una información certera, oportuna, rápida y correcta para la organización manifiesta en un eficiente manejo de la información para así lograr una satisfacción plena de los clientes y de esta manera la empresa poder llevar un buen manejo y manipulación de sus inventarios, balances, facturas, clientes, productos, proveedores, entre otros",
        programa: "Ingeniería en Software",
        proceso: "Estancia",
        vacantes: 5,
        periodo: "Enero-Abril 2023",
        modalidad: "Presencial",
        asesor: "John Man Doe",
        empresa: "Software Inc",
        telefono: "962 289 9278",
        titular: "Carlos Horacio García Quintanilla",
        cargo: "Director General",
        correo: "CarlosHGarciaQ@SoftwareInc.com",
        entidad: "Chiapas",
        ciudad: "Tapachula",
        cp: "30700",
        colonia: "Centro",
        calle: "Primera Oriente",
        numero: "4"
    },
    {
        nombre: "Desarrollo de Página Web",
        objetivo: "Desarrollar e implentar un sistema de administración de ventas para optimizar los procesos de gestión de ventas de servicios académicos",
        justificacion: "Garantizar una información certera, oportuna, rápida y correcta para la organización manifiesta en un eficiente manejo de la información para así lograr una satisfacción plena de los clientes y de esta manera la empresa poder llevar un buen manejo y manipulación de sus inventarios, balances, facturas, clientes, productos, proveedores, entre otros",
        programa: "Ingeniería en Software",
        proceso: "Estancia",
        vacantes: 5,
        periodo: "Enero-Abril 2023",
        modalidad: "Presencial",
        asesor: "John Man Doe",
        empresa: "Software Inc",
        telefono: "962 289 9278",
        titular: "Carlos Horacio García Quintanilla",
        cargo: "Director General",
        correo: "CarlosHGarciaQ@SoftwareInc.com",
        entidad: "Chiapas",
        ciudad: "Tapachula",
        cp: "30700",
        colonia: "Centro",
        calle: "Primera Oriente",
        numero: "4"
    },
    {
        nombre: "Implementación de Sistema de Ventas",
        objetivo: "Desarrollar e implentar un sistema de administración de ventas para optimizar los procesos de gestión de ventas de servicios académicos",
        justificacion: "Garantizar una información certera, oportuna, rápida y correcta para la organización manifiesta en un eficiente manejo de la información para así lograr una satisfacción plena de los clientes y de esta manera la empresa poder llevar un buen manejo y manipulación de sus inventarios, balances, facturas, clientes, productos, proveedores, entre otros",
        programa: "Ingeniería en Software",
        proceso: "Estancia",
        vacantes: 5,
        periodo: "Enero-Abril 2023",
        modalidad: "Presencial",
        asesor: "John Man Doe",
        empresa: "Software Inc",
        telefono: "962 289 9278",
        titular: "Carlos Horacio García Quintanilla",
        cargo: "Director General",
        correo: "CarlosHGarciaQ@SoftwareInc.com",
        entidad: "Chiapas",
        ciudad: "Tapachula",
        cp: "30700",
        colonia: "Centro",
        calle: "Primera Oriente",
        numero: "4"
    },
    {
        nombre: "Desarrollo Sistema de Cableado",
        objetivo: "Desarrollar e implentar un sistema de administración de ventas para optimizar los procesos de gestión de ventas de servicios académicos",
        justificacion: "Garantizar una información certera, oportuna, rápida y correcta para la organización manifiesta en un eficiente manejo de la información para así lograr una satisfacción plena de los clientes y de esta manera la empresa poder llevar un buen manejo y manipulación de sus inventarios, balances, facturas, clientes, productos, proveedores, entre otros",
        programa: "Ingeniería en Energía",
        proceso: "Estancia",
        vacantes: 5,
        periodo: "Enero-Abril 2023",
        modalidad: "Presencial",
        asesor: "John Man Doe",
        empresa: "Software Inc",
        telefono: "962 289 9278",
        titular: "Carlos Horacio García Quintanilla",
        cargo: "Director General",
        correo: "CarlosHGarciaQ@SoftwareInc.com",
        entidad: "Chiapas",
        ciudad: "Tapachula",
        cp: "30700",
        colonia: "Centro",
        calle: "Primera Oriente",
        numero: "4"
    },
    {
        nombre: "Desarrollo de Energía",
        objetivo: "Desarrollar e implentar un sistema de administración de ventas para optimizar los procesos de gestión de ventas de servicios académicos",
        justificacion: "Garantizar una información certera, oportuna, rápida y correcta para la organización manifiesta en un eficiente manejo de la información para así lograr una satisfacción plena de los clientes y de esta manera la empresa poder llevar un buen manejo y manipulación de sus inventarios, balances, facturas, clientes, productos, proveedores, entre otros",
        programa: "Ingeniería en Energía",
        proceso: "Estancia",
        vacantes: 5,
        periodo: "Enero-Abril 2023",
        modalidad: "Presencial",
        asesor: "John Man Doe",
        empresa: "Software Inc",
        telefono: "962 289 9278",
        titular: "Carlos Horacio García Quintanilla",
        cargo: "Director General",
        correo: "CarlosHGarciaQ@SoftwareInc.com",
        entidad: "Chiapas",
        ciudad: "Tapachula",
        cp: "30700",
        colonia: "Centro",
        calle: "Primera Oriente",
        numero: "4"
    }
];
export default Projects;